# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  # Main branch - all updates
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
    target-branch: "main"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "kthoms"
    target-branch: "main"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:00"
    reviewers:
      - "kthoms"
    target-branch: "main"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Release 1.0.x branch - patch updates only
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
      time: "01:30"
    target-branch: "release/1.0.x"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "01:30"
    reviewers:
      - "kthoms"
    target-branch: "release/1.0.x"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:30"
    reviewers:
      - "kthoms"
    target-branch: "release/1.0.x"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]